name: 'publish-kolor'
on:
  push:
    branches: [master]
    paths:
      - 'kolor/**' 

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'windows-latest'
            args: ''
          - platform: 'macos-latest'
            args: ''
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: install bun
        uses: oven-sh/setup-bun@v2
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: install app dependencies
        run: |
          cd kolor
          bun install

      - name: build tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: ./kolor
          tagName: kolor-v__VERSION__
          releaseName: 'Kolor App v__VERSION__'
          releaseBody: 'kolor - Tauri Practice App Build Completed.'
          releaseDraft: true
          args: ${{ matrix.args }}
